package:
  name: ruby
  version: 1.9.3

source:
  fn: ruby-1.9.3-p551.tar.gz 
  url: http://cache.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-p551.tar.gz
  sha256: bb5be55cd1f49c95bb05b6f587701376b53d310eb1bb7c76fbd445a1c75b51e8

test:
  commands:
    - ruby --version
    - gem --version

    - ruby -e 'puts "Hi, from Ruby!"'
    - ruby -r rubygems -e 'puts "Has gems."; exit 0'
    - ruby -r openssl -r readline -r yaml -r zlib -e 'puts "Has all dependencies."; exit 0'

requirements:
  build:
    - openssl
    - readline
    - tk
    - yaml
    - zlib
  run:
    - openssl
    - readline
    - tk
    - yaml
    - zlib

about:
  home: http://www.ruby-lang.org
  license: BSD

