package:
  name: gitsh
  version: v0.9

source:
  fn: gitsh-0.9.tar.gz
  url: https://github.com/thoughtbot/gitsh/releases/download/v0.9/gitsh-0.9.tar.gz
  sha256: bd6e278e60b71cc30734ae199154c797554b278bd7f813d1d5783a80c5bd1891

build:
  #number: 1
  detect_binary_files_with_prefix: true

test:
  commands:
    - gitsh --version

requirements:
  build:
    - ruby ==1.9.3
  run:
    - ruby ==1.9.3

about:
  home: https://github.com/thoughtbot/gitsh
  license: BSD

